services:
  - type: web
    name: fixia
    runtime: node
    plan: free
    region: ohio
    buildCommand: npm ci --include=dev && npm run build
    preDeployCommand: npx prisma migrate deploy
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
